docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: 'pars-{component}'
site_description: ''
repo_url: 'https://github.com/pars/pars-{component}'
